export const CREATE_BACKLOG_TASK = 'TASK/CREATE_BACKLOG_TASK';
export const CREATE_READY_TASK = 'TASK/CREATE_READY_TASK';
export const REMOVE_BACKLOG_TASK = 'TASK/REMOVE_BACKLOG_TASK';
export const CREATE_INPROGRESS_TASK = 'TASK/CREATE_INPROGRESS_TASK';
export const REMOVE_READY_TASK = 'TASK/REMOVE_READY_TASK';
export const CREATE_FINISHED_TASK = 'TASK/CREATE_FINISHED_TASK';
export const REMOVE_INPROGRESS_TASK = 'TASK/REMOVE_INPROGRESS_TASK';
